In [10]:
import pandas as pd
import numpy as np

In [11]:
#df_qtrly = pd.read_csv('df_qtrly_sales_flat.csv').set_index('Unnamed: 0')
df_annual = pd.read_csv('df_annual_sales_flat.csv').set_index('Unnamed: 0')
df_balancesheet = pd.read_csv('df_other_fundamentals.csv').set_index('Unnamed: 0')

# This is not monthly but 3 yrs delta return
#df_bhav_return = pd.read_csv('df_bhav_1yr_delta.csv').set_index('Unnamed: 0')
df_bhav_return = pd.read_csv('df_bhav_2yr_delta.csv').set_index('Unnamed: 0')
df_bhav_monthly_delta = pd.read_csv('df_bhav_monthly_delta.csv').set_index('Unnamed: 0')

In [12]:
#df_qtrly.head(3)

In [13]:
df_annual.head(3)

,Tikr,Sales_2010,Sales_2011,Sales_2012,Sales_2013,Sales_2014,Sales_2015,Sales_2016,Sales_2017,Sales_2018,...,OPM__2012_YoY,OPM__2013_YoY,OPM__2014_YoY,OPM__2015_YoY,OPM__2016_YoY,OPM__2017_YoY,OPM__2018_YoY,OPM__2019_YoY,OPM__2020_YoY,OPM__2021_YoY
Unnamed: 0,,,,,,,,,,,,,,,,,,,,,
0,20MICRONS,175.00,234.00,262.0,275.00,288.00,311.00,333.00,357.00,385.00,...,20.000000,0.0,-33.333333,-12.500000,71.428571,16.666667,0.000000,0.000000,-14.285714,0.0
1,21STCENMGM,1.18,23.45,-4.2,0.12,1.08,37.13,2.88,1.92,10.51,...,-100.000000,-inf,-96.376490,-771.850252,-61.680240,-133.501119,-757.595993,4.303123,-100.000000,NaN
2,3IINFOTECH,692.00,963.00,1120.0,1198.00,1278.00,1437.00,1431.00,1521.00,1833.00,...,-11.111111,-12.5,0.000000,14.285714,12.500000,11.111111,-10.000000,0.000000,-22.222222,0.0

In [14]:
df_bhav_monthly_delta.head(3)

,2010_01_CLOSE,2010_02_CLOSE,2010_03_CLOSE,2010_04_CLOSE,2010_05_CLOSE,2010_06_CLOSE,2010_07_CLOSE,2010_08_CLOSE,2010_09_CLOSE,2010_10_CLOSE,...,2021_04_CLOSE,2021_05_CLOSE,2021_06_CLOSE,2021_07_CLOSE,2021_08_CLOSE,2021_09_CLOSE,2021_10_CLOSE,2021_11_CLOSE,2021_12_CLOSE,Tikr
Unnamed: 0,,,,,,,,,,,,,,,,,,,,,
0,7.146723,-12.95967,-5.641026,1.686019,-3.625877,3.163590,22.632875,7.419087,9.964850,-4.018056,...,2.021803,48.826517,14.501908,2.401271,-11.286822,1.537922,3.635973,0.361221,-0.132383,20MICRONS
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-9.074075,18.207739,41.540318,12.172852,29.571353,43.551092,21.353556,12.980770,-15.234041,21STCENMGM
2,-1.313365,4.87009,16.162459,2.486186,1.586076,13.756744,13.179531,12.878662,11.073646,1.899978,...,-4.133668,-4.439297,-0.966247,-2.748936,-3.313726,4.517514,4.173737,0.390809,-3.151370,3MINDIA

In [15]:
df_bhav_return[df_bhav_return['Tikr'] == 'NIFTY50']

Empty DataFrame
Columns: [2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, Tikr]
Index: []

In [16]:
# Merging the three dataframes
#df_fundamentals = pd.merge(df_annual, df_qtrly, how='left',left_on=['Tikr'], right_on=['Tikr'])
df_fundamentals = pd.merge(df_annual, df_balancesheet, how='left',left_on=['Tikr'], right_on=['Tikr'])
df_merge =  pd.merge(df_fundamentals,df_bhav_return, how='left',left_on=['Tikr'], right_on=['Tikr'])
df_merge =  pd.merge(df_merge,df_bhav_monthly_delta, how='left',left_on=['Tikr'], right_on=['Tikr'])
pd.DataFrame(df_merge.columns).to_clipboard()
#pd.DataFrame(df_merge).to_clipboard()

In [17]:
# Identifying columns having null values
null_values = df_merge.isna().sum()/len(df_merge)
pd.DataFrame(null_values).to_clipboard()

In [18]:
df_bhav_return.columns

Index(['2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018', '2019',
       '2020', 'Tikr'],
      dtype='object')

In [19]:
# Merging Industry

In [21]:
# As a next step we need to select the 5 year columns for training and the next 1 year return as y variable
# list_2013 = ['Tikr','Sales_2010','Sales_2011','Sales_2012',
#             'Sales_2011_YoY','Sales_2012_YoY',
#             'Revenue_2010','Revenue_2011','Revenue_2012',
#             'Revenue_2011_YoY','Revenue_2012_YoY',
#             'Expenses_2010','Expenses_2011','Expenses_2012',
#             'Expenses_2011_YoY','Expenses_2012_YoY',
#             'Net_Profit_2010','Net_Profit_2011','Net_Profit_2012',
#             'Net_Profit_2011_YoY','Net_Profit_2012_YoY',
#             'Operating_Profit_2010','Operating_Profit_2011','Operating_Profit_2012',
#             'Operating_Profit_2011_YoY','Operating_Profit_2012_YoY',
#             'EPS_in_Rs_2010','EPS_in_Rs_2011','EPS_in_Rs_2012',
#             'EPS_in_Rs_2011_YoY','EPS_in_Rs_2012_YoY',
#             'Tax__2010','Tax__2011','Tax__2012',
#             'Tax__2011_YoY','Tax__2012_YoY',
#             'OPM__2010','OPM__2011','OPM__2012',
#             'OPM__2011_YoY','OPM__2012_YoY','2015']

list_2015 = ['Tikr',
            'Sales_2010','Sales_2011','Sales_2012','Sales_2013','Sales_2014',
            'Sales_2011_YoY','Sales_2012_YoY','Sales_2013_YoY','Sales_2014_YoY',
            'Revenue_2010','Revenue_2011','Revenue_2012','Revenue_2013','Revenue_2014',
            'Revenue_2011_YoY','Revenue_2012_YoY','Revenue_2013_YoY','Revenue_2014_YoY',
            'Expenses_2010','Expenses_2011','Expenses_2012','Expenses_2013','Expenses_2014',
            'Expenses_2011_YoY','Expenses_2012_YoY','Expenses_2013_YoY','Expenses_2014_YoY',
            'Net_Profit_2010','Net_Profit_2011','Net_Profit_2012','Net_Profit_2013','Net_Profit_2014',
            'Net_Profit_2011_YoY','Net_Profit_2012_YoY','Net_Profit_2013_YoY','Net_Profit_2014_YoY',
            'Operating_Profit_2010','Operating_Profit_2011','Operating_Profit_2012','Operating_Profit_2013','Operating_Profit_2014',
            'Operating_Profit_2011_YoY','Operating_Profit_2012_YoY','Operating_Profit_2013_YoY','Operating_Profit_2014_YoY',
            'EPS_in_Rs_2010','EPS_in_Rs_2011','EPS_in_Rs_2012','EPS_in_Rs_2013','EPS_in_Rs_2014',
            'EPS_in_Rs_2011_YoY','EPS_in_Rs_2012_YoY','EPS_in_Rs_2013_YoY','EPS_in_Rs_2014_YoY',
            'Tax__2010','Tax__2011','Tax__2012','Tax__2013','Tax__2014',
            'Tax__2011_YoY','Tax__2012_YoY','Tax__2013_YoY','Tax__2014_YoY',
            'OPM__2010','OPM__2011','OPM__2012','OPM__2013','OPM__2014',
            'OPM__2011_YoY','OPM__2012_YoY','OPM__2013_YoY','OPM__2014_YoY',
            'Other_Assets_2010','Other_Assets_2011','Other_Assets_2012','Other_Assets_2013','Other_Assets_2014',
            'Other_Assets_2011_YoY','Other_Assets_2012_YoY','Other_Assets_2013_YoY','Other_Assets_2014_YoY',
            'Total_Liabilities_2010','Total_Liabilities_2011','Total_Liabilities_2012','Total_Liabilities_2013','Total_Liabilities_2014',
            'Total_Liabilities_2011_YoY','Total_Liabilities_2012_YoY','Total_Liabilities_2013_YoY','Total_Liabilities_2014_YoY',
            'Share_Capital_2010','Share_Capital_2011','Share_Capital_2012','Share_Capital_2013','Share_Capital_2014',
            'Share_Capital_2011_YoY','Share_Capital_2012_YoY','Share_Capital_2013_YoY','Share_Capital_2014_YoY',
            'Investments_2010','Investments_2011','Investments_2012','Investments_2013','Investments_2014',
            'Investments_2011_YoY','Investments_2012_YoY','Investments_2013_YoY','Investments_2014_YoY',
            'Borrowings_2010','Borrowings_2011','Borrowings_2012','Borrowings_2013','Borrowings_2014',
            'Borrowings_2011_YoY','Borrowings_2012_YoY','Borrowings_2013_YoY','Borrowings_2014_YoY',
            'Reserves_2010','Reserves_2011','Reserves_2012','Reserves_2013','Reserves_2014',
            'Reserves_2011_YoY','Reserves_2012_YoY','Reserves_2013_YoY','Reserves_2014_YoY',
            'Total_Assets_2010','Total_Assets_2011','Total_Assets_2012','Total_Assets_2013','Total_Assets_2014',
            'Total_Assets_2011_YoY','Total_Assets_2012_YoY','Total_Assets_2013_YoY','Total_Assets_2014_YoY',
            'Fixed_Assets_2010','Fixed_Assets_2011','Fixed_Assets_2012','Fixed_Assets_2013','Fixed_Assets_2014',
            'Fixed_Assets_2011_YoY','Fixed_Assets_2012_YoY','Fixed_Assets_2013_YoY','Fixed_Assets_2014_YoY',
            'Other_Liabilities_2010','Other_Liabilities_2011','Other_Liabilities_2012','Other_Liabilities_2013','Other_Liabilities_2014',
            'Other_Liabilities_2011_YoY','Other_Liabilities_2012_YoY','Other_Liabilities_2013_YoY','Other_Liabilities_2014_YoY',
            'CWIP_2010','CWIP_2011','CWIP_2012','CWIP_2013','CWIP_2014',
            'CWIP_2011_YoY','CWIP_2012_YoY','CWIP_2013_YoY','CWIP_2014_YoY',
            'Cash_from_Investing_Activity_2010','Cash_from_Investing_Activity_2011','Cash_from_Investing_Activity_2012','Cash_from_Investing_Activity_2013','Cash_from_Investing_Activity_2014',
            'Cash_from_Investing_Activity_2011_YoY','Cash_from_Investing_Activity_2012_YoY','Cash_from_Investing_Activity_2013_YoY','Cash_from_Investing_Activity_2014_YoY',
            'Cash_from_Operating_Activity_2010','Cash_from_Operating_Activity_2011','Cash_from_Operating_Activity_2012','Cash_from_Operating_Activity_2013','Cash_from_Operating_Activity_2014',
            'Cash_from_Operating_Activity_2011_YoY','Cash_from_Operating_Activity_2012_YoY','Cash_from_Operating_Activity_2013_YoY','Cash_from_Operating_Activity_2014_YoY',
            'Cash_from_Financing_Activity_2010','Cash_from_Financing_Activity_2011','Cash_from_Financing_Activity_2012','Cash_from_Financing_Activity_2013','Cash_from_Financing_Activity_2014',
            'Cash_from_Financing_Activity_2011_YoY','Cash_from_Financing_Activity_2012_YoY','Cash_from_Financing_Activity_2013_YoY','Cash_from_Financing_Activity_2014_YoY',
            'Net_Cash_Flow_2010','Net_Cash_Flow_2011','Net_Cash_Flow_2012','Net_Cash_Flow_2013','Net_Cash_Flow_2014',
            'Net_Cash_Flow_2011_YoY','Net_Cash_Flow_2012_YoY','Net_Cash_Flow_2013_YoY','Net_Cash_Flow_2014_YoY',
            'Share_Capital_%_2010','Share_Capital_%_2011','Share_Capital_%_2012','Share_Capital_%_2013','Share_Capital_%_2014',
            'Reserves_%_2010','Reserves_%_2011','Reserves_%_2012','Reserves_%_2013','Reserves_%_2014',
            'Borrowings_%_2010','Borrowings_%_2011','Borrowings_%_2012','Borrowings_%_2013','Borrowings_%_2014',
            'Other_Liabilities_%_2010','Other_Liabilities_%_2011','Other_Liabilities_%_2012','Other_Liabilities_%_2013','Other_Liabilities_%_2014',
            'Fixed_Assets_%_2010','Fixed_Assets_%_2011','Fixed_Assets_%_2012','Fixed_Assets_%_2013','Fixed_Assets_%_2014',
            'CWIP_%_2010','CWIP_%_2011','CWIP_%_2012','CWIP_%_2013','CWIP_%_2014',
            'Investments_%_2010','Investments_%_2011','Investments_%_2012','Investments_%_2013','Investments_%_2014',
            'Other_Assets_%_2010','Other_Assets_%_2011','Other_Assets_%_2012','Other_Assets_%_2013','Other_Assets_%_2014',
            'MarketCap','CapFlag','LageCap','MidCap','SmallCap','TinyCap','Industry',
            '2014_01_CLOSE','2014_02_CLOSE','2014_03_CLOSE','2014_04_CLOSE','2014_05_CLOSE','2014_06_CLOSE','2014_07_CLOSE','2014_08_CLOSE','2014_09_CLOSE','2014_10_CLOSE','2014_11_CLOSE','2014_12_CLOSE',
            '2015']

list_2016 = ['Tikr',
            'Sales_2011','Sales_2012','Sales_2013','Sales_2014','Sales_2015',
            'Sales_2012_YoY','Sales_2013_YoY','Sales_2014_YoY','Sales_2015_YoY',
            'Revenue_2011','Revenue_2012','Revenue_2013','Revenue_2014','Revenue_2015',
            'Revenue_2012_YoY','Revenue_2013_YoY','Revenue_2014_YoY','Revenue_2015_YoY',
            'Expenses_2011','Expenses_2012','Expenses_2013','Expenses_2014','Expenses_2015',
            'Expenses_2012_YoY','Expenses_2013_YoY','Expenses_2014_YoY','Expenses_2015_YoY',
            'Net_Profit_2011','Net_Profit_2012','Net_Profit_2013','Net_Profit_2014','Net_Profit_2015',
            'Net_Profit_2012_YoY','Net_Profit_2013_YoY','Net_Profit_2014_YoY','Net_Profit_2015_YoY',
            'Operating_Profit_2011','Operating_Profit_2012','Operating_Profit_2013','Operating_Profit_2014','Operating_Profit_2015',
            'Operating_Profit_2012_YoY','Operating_Profit_2013_YoY','Operating_Profit_2014_YoY','Operating_Profit_2015_YoY',
            'EPS_in_Rs_2011','EPS_in_Rs_2012','EPS_in_Rs_2013','EPS_in_Rs_2014','EPS_in_Rs_2015',
            'EPS_in_Rs_2012_YoY','EPS_in_Rs_2013_YoY','EPS_in_Rs_2014_YoY','EPS_in_Rs_2015_YoY',
            'Tax__2011','Tax__2012','Tax__2013','Tax__2014','Tax__2015',
            'Tax__2012_YoY','Tax__2013_YoY','Tax__2014_YoY','Tax__2015_YoY',
            'OPM__2011','OPM__2012','OPM__2013','OPM__2014','OPM__2015',
            'OPM__2012_YoY','OPM__2013_YoY','OPM__2014_YoY','OPM__2015_YoY',
            'Other_Assets_2011','Other_Assets_2012','Other_Assets_2013','Other_Assets_2014','Other_Assets_2015',
            'Other_Assets_2012_YoY','Other_Assets_2013_YoY','Other_Assets_2014_YoY','Other_Assets_2015_YoY',
            'Total_Liabilities_2011','Total_Liabilities_2012','Total_Liabilities_2013','Total_Liabilities_2014','Total_Liabilities_2015',
            'Total_Liabilities_2012_YoY','Total_Liabilities_2013_YoY','Total_Liabilities_2014_YoY','Total_Liabilities_2015_YoY',
            'Share_Capital_2011','Share_Capital_2012','Share_Capital_2013','Share_Capital_2014','Share_Capital_2015',
            'Share_Capital_2012_YoY','Share_Capital_2013_YoY','Share_Capital_2014_YoY','Share_Capital_2015_YoY',
            'Investments_2011','Investments_2012','Investments_2013','Investments_2014','Investments_2015',
            'Investments_2012_YoY','Investments_2013_YoY','Investments_2014_YoY','Investments_2015_YoY',
            'Borrowings_2011','Borrowings_2012','Borrowings_2013','Borrowings_2014','Borrowings_2015',
            'Borrowings_2012_YoY','Borrowings_2013_YoY','Borrowings_2014_YoY','Borrowings_2015_YoY',
            'Reserves_2011','Reserves_2012','Reserves_2013','Reserves_2014','Reserves_2015',
            'Reserves_2012_YoY','Reserves_2013_YoY','Reserves_2014_YoY','Reserves_2015_YoY',
            'Total_Assets_2011','Total_Assets_2012','Total_Assets_2013','Total_Assets_2014','Total_Assets_2015',
            'Total_Assets_2012_YoY','Total_Assets_2013_YoY','Total_Assets_2014_YoY','Total_Assets_2015_YoY',
            'Fixed_Assets_2011','Fixed_Assets_2012','Fixed_Assets_2013','Fixed_Assets_2014','Fixed_Assets_2015',
            'Fixed_Assets_2012_YoY','Fixed_Assets_2013_YoY','Fixed_Assets_2014_YoY','Fixed_Assets_2015_YoY',
            'Other_Liabilities_2011','Other_Liabilities_2012','Other_Liabilities_2013','Other_Liabilities_2014','Other_Liabilities_2015',
            'Other_Liabilities_2012_YoY','Other_Liabilities_2013_YoY','Other_Liabilities_2014_YoY','Other_Liabilities_2015_YoY',
            'CWIP_2011','CWIP_2012','CWIP_2013','CWIP_2014','CWIP_2015',
            'CWIP_2012_YoY','CWIP_2013_YoY','CWIP_2014_YoY','CWIP_2015_YoY',
            'Cash_from_Investing_Activity_2011','Cash_from_Investing_Activity_2012','Cash_from_Investing_Activity_2013','Cash_from_Investing_Activity_2014','Cash_from_Investing_Activity_2015',
            'Cash_from_Investing_Activity_2012_YoY','Cash_from_Investing_Activity_2013_YoY','Cash_from_Investing_Activity_2014_YoY','Cash_from_Investing_Activity_2015_YoY',
            'Cash_from_Operating_Activity_2011','Cash_from_Operating_Activity_2012','Cash_from_Operating_Activity_2013','Cash_from_Operating_Activity_2014','Cash_from_Operating_Activity_2015',
            'Cash_from_Operating_Activity_2012_YoY','Cash_from_Operating_Activity_2013_YoY','Cash_from_Operating_Activity_2014_YoY','Cash_from_Operating_Activity_2015_YoY',
            'Cash_from_Financing_Activity_2011','Cash_from_Financing_Activity_2012','Cash_from_Financing_Activity_2013','Cash_from_Financing_Activity_2014','Cash_from_Financing_Activity_2015',
            'Cash_from_Financing_Activity_2012_YoY','Cash_from_Financing_Activity_2013_YoY','Cash_from_Financing_Activity_2014_YoY','Cash_from_Financing_Activity_2015_YoY',
            'Net_Cash_Flow_2011','Net_Cash_Flow_2012','Net_Cash_Flow_2013','Net_Cash_Flow_2014','Net_Cash_Flow_2015',
            'Net_Cash_Flow_2012_YoY','Net_Cash_Flow_2013_YoY','Net_Cash_Flow_2014_YoY','Net_Cash_Flow_2015_YoY',
            'Share_Capital_%_2011','Share_Capital_%_2012','Share_Capital_%_2013','Share_Capital_%_2014','Share_Capital_%_2015',
            'Reserves_%_2011','Reserves_%_2012','Reserves_%_2013','Reserves_%_2014','Reserves_%_2015',
            'Borrowings_%_2011','Borrowings_%_2012','Borrowings_%_2013','Borrowings_%_2014','Borrowings_%_2015',
            'Other_Liabilities_%_2011','Other_Liabilities_%_2012','Other_Liabilities_%_2013','Other_Liabilities_%_2014','Other_Liabilities_%_2015',
            'Fixed_Assets_%_2011','Fixed_Assets_%_2012','Fixed_Assets_%_2013','Fixed_Assets_%_2014','Fixed_Assets_%_2015',
            'CWIP_%_2011','CWIP_%_2012','CWIP_%_2013','CWIP_%_2014','CWIP_%_2015',
            'Investments_%_2011','Investments_%_2012','Investments_%_2013','Investments_%_2014','Investments_%_2015',
            'Other_Assets_%_2011','Other_Assets_%_2012','Other_Assets_%_2013','Other_Assets_%_2014','Other_Assets_%_2015',
            'MarketCap','CapFlag','LageCap','MidCap','SmallCap','TinyCap','Industry',
            '2015_01_CLOSE','2015_02_CLOSE','2015_03_CLOSE','2015_04_CLOSE','2015_05_CLOSE','2015_06_CLOSE','2015_07_CLOSE','2015_08_CLOSE','2015_09_CLOSE','2015_10_CLOSE','2015_11_CLOSE','2015_12_CLOSE',
            '2016']

list_2017 = ['Tikr',
            'Sales_2012','Sales_2013','Sales_2014','Sales_2015','Sales_2016',
            'Sales_2013_YoY','Sales_2014_YoY','Sales_2015_YoY','Sales_2016_YoY',
            'Revenue_2012','Revenue_2013','Revenue_2014','Revenue_2015','Revenue_2016',
            'Revenue_2013_YoY','Revenue_2014_YoY','Revenue_2015_YoY','Revenue_2016_YoY',
            'Expenses_2012','Expenses_2013','Expenses_2014','Expenses_2015','Expenses_2016',
            'Expenses_2013_YoY','Expenses_2014_YoY','Expenses_2015_YoY','Expenses_2016_YoY',
            'Net_Profit_2012','Net_Profit_2013','Net_Profit_2014','Net_Profit_2015','Net_Profit_2016',
            'Net_Profit_2013_YoY','Net_Profit_2014_YoY','Net_Profit_2015_YoY','Net_Profit_2016_YoY',
            'Operating_Profit_2012','Operating_Profit_2013','Operating_Profit_2014','Operating_Profit_2015','Operating_Profit_2016',
            'Operating_Profit_2013_YoY','Operating_Profit_2014_YoY','Operating_Profit_2015_YoY','Operating_Profit_2016_YoY',
            'EPS_in_Rs_2012','EPS_in_Rs_2013','EPS_in_Rs_2014','EPS_in_Rs_2015','EPS_in_Rs_2016',
            'EPS_in_Rs_2013_YoY','EPS_in_Rs_2014_YoY','EPS_in_Rs_2015_YoY','EPS_in_Rs_2016_YoY',
            'Tax__2012','Tax__2013','Tax__2014','Tax__2015','Tax__2016',
            'Tax__2013_YoY','Tax__2014_YoY','Tax__2015_YoY','Tax__2016_YoY',
            'OPM__2012','OPM__2013','OPM__2014','OPM__2015','OPM__2016',
            'OPM__2013_YoY','OPM__2014_YoY','OPM__2015_YoY','OPM__2016_YoY',
            'Other_Assets_2012','Other_Assets_2013','Other_Assets_2014','Other_Assets_2015','Other_Assets_2016',
            'Other_Assets_2013_YoY','Other_Assets_2014_YoY','Other_Assets_2015_YoY','Other_Assets_2016_YoY',
            'Total_Liabilities_2012','Total_Liabilities_2013','Total_Liabilities_2014','Total_Liabilities_2015','Total_Liabilities_2016',
            'Total_Liabilities_2013_YoY','Total_Liabilities_2014_YoY','Total_Liabilities_2015_YoY','Total_Liabilities_2016_YoY',
            'Share_Capital_2012','Share_Capital_2013','Share_Capital_2014','Share_Capital_2015','Share_Capital_2016',
            'Share_Capital_2013_YoY','Share_Capital_2014_YoY','Share_Capital_2015_YoY','Share_Capital_2016_YoY',
            'Investments_2012','Investments_2013','Investments_2014','Investments_2015','Investments_2016',
            'Investments_2013_YoY','Investments_2014_YoY','Investments_2015_YoY','Investments_2016_YoY',
            'Borrowings_2012','Borrowings_2013','Borrowings_2014','Borrowings_2015','Borrowings_2016',
            'Borrowings_2013_YoY','Borrowings_2014_YoY','Borrowings_2015_YoY','Borrowings_2016_YoY',
            'Reserves_2012','Reserves_2013','Reserves_2014','Reserves_2015','Reserves_2016',
            'Reserves_2013_YoY','Reserves_2014_YoY','Reserves_2015_YoY','Reserves_2016_YoY',
            'Total_Assets_2012','Total_Assets_2013','Total_Assets_2014','Total_Assets_2015','Total_Assets_2016',
            'Total_Assets_2013_YoY','Total_Assets_2014_YoY','Total_Assets_2015_YoY','Total_Assets_2016_YoY',
            'Fixed_Assets_2012','Fixed_Assets_2013','Fixed_Assets_2014','Fixed_Assets_2015','Fixed_Assets_2016',
            'Fixed_Assets_2013_YoY','Fixed_Assets_2014_YoY','Fixed_Assets_2015_YoY','Fixed_Assets_2016_YoY',
            'Other_Liabilities_2012','Other_Liabilities_2013','Other_Liabilities_2014','Other_Liabilities_2015','Other_Liabilities_2016',
            'Other_Liabilities_2013_YoY','Other_Liabilities_2014_YoY','Other_Liabilities_2015_YoY','Other_Liabilities_2016_YoY',
            'CWIP_2012','CWIP_2013','CWIP_2014','CWIP_2015','CWIP_2016',
            'CWIP_2013_YoY','CWIP_2014_YoY','CWIP_2015_YoY','CWIP_2016_YoY',
            'Cash_from_Investing_Activity_2012','Cash_from_Investing_Activity_2013','Cash_from_Investing_Activity_2014','Cash_from_Investing_Activity_2015','Cash_from_Investing_Activity_2016',
            'Cash_from_Investing_Activity_2013_YoY','Cash_from_Investing_Activity_2014_YoY','Cash_from_Investing_Activity_2015_YoY','Cash_from_Investing_Activity_2016_YoY',
            'Cash_from_Operating_Activity_2012','Cash_from_Operating_Activity_2013','Cash_from_Operating_Activity_2014','Cash_from_Operating_Activity_2015','Cash_from_Operating_Activity_2016',
            'Cash_from_Operating_Activity_2013_YoY','Cash_from_Operating_Activity_2014_YoY','Cash_from_Operating_Activity_2015_YoY','Cash_from_Operating_Activity_2016_YoY',
            'Cash_from_Financing_Activity_2012','Cash_from_Financing_Activity_2013','Cash_from_Financing_Activity_2014','Cash_from_Financing_Activity_2015','Cash_from_Financing_Activity_2016',
            'Cash_from_Financing_Activity_2013_YoY','Cash_from_Financing_Activity_2014_YoY','Cash_from_Financing_Activity_2015_YoY','Cash_from_Financing_Activity_2016_YoY',
            'Net_Cash_Flow_2012','Net_Cash_Flow_2013','Net_Cash_Flow_2014','Net_Cash_Flow_2015','Net_Cash_Flow_2016',
            'Net_Cash_Flow_2013_YoY','Net_Cash_Flow_2014_YoY','Net_Cash_Flow_2015_YoY','Net_Cash_Flow_2016_YoY',
            'Share_Capital_%_2012','Share_Capital_%_2013','Share_Capital_%_2014','Share_Capital_%_2015','Share_Capital_%_2016',
            'Reserves_%_2012','Reserves_%_2013','Reserves_%_2014','Reserves_%_2015','Reserves_%_2016',
            'Borrowings_%_2012','Borrowings_%_2013','Borrowings_%_2014','Borrowings_%_2015','Borrowings_%_2016',
            'Other_Liabilities_%_2012','Other_Liabilities_%_2013','Other_Liabilities_%_2014','Other_Liabilities_%_2015','Other_Liabilities_%_2016',
            'Fixed_Assets_%_2012','Fixed_Assets_%_2013','Fixed_Assets_%_2014','Fixed_Assets_%_2015','Fixed_Assets_%_2016',
            'CWIP_%_2012','CWIP_%_2013','CWIP_%_2014','CWIP_%_2015','CWIP_%_2016',
            'Investments_%_2012','Investments_%_2013','Investments_%_2014','Investments_%_2015','Investments_%_2016',
            'Other_Assets_%_2012','Other_Assets_%_2013','Other_Assets_%_2014','Other_Assets_%_2015','Other_Assets_%_2016',
            'MarketCap','CapFlag','LageCap','MidCap','SmallCap','TinyCap','Industry',
            '2016_01_CLOSE','2016_02_CLOSE','2016_03_CLOSE','2016_04_CLOSE','2016_05_CLOSE','2016_06_CLOSE','2016_07_CLOSE','2016_08_CLOSE','2016_09_CLOSE','2016_10_CLOSE','2016_11_CLOSE','2016_12_CLOSE',
            '2017']
    
list_2018 = ['Tikr',
            'Sales_2013','Sales_2014','Sales_2015','Sales_2016','Sales_2017',
            'Sales_2014_YoY','Sales_2015_YoY','Sales_2016_YoY','Sales_2017_YoY',
            'Revenue_2013','Revenue_2014','Revenue_2015','Revenue_2016','Revenue_2017',
            'Revenue_2014_YoY','Revenue_2015_YoY','Revenue_2016_YoY','Revenue_2017_YoY',
            'Expenses_2013','Expenses_2014','Expenses_2015','Expenses_2016','Expenses_2017',
            'Expenses_2014_YoY','Expenses_2015_YoY','Expenses_2016_YoY','Expenses_2017_YoY',
            'Net_Profit_2013','Net_Profit_2014','Net_Profit_2015','Net_Profit_2016','Net_Profit_2017',
            'Net_Profit_2014_YoY','Net_Profit_2015_YoY','Net_Profit_2016_YoY','Net_Profit_2017_YoY',
            'Operating_Profit_2013','Operating_Profit_2014','Operating_Profit_2015','Operating_Profit_2016','Operating_Profit_2017',
            'Operating_Profit_2014_YoY','Operating_Profit_2015_YoY','Operating_Profit_2016_YoY','Operating_Profit_2017_YoY',
            'EPS_in_Rs_2013','EPS_in_Rs_2014','EPS_in_Rs_2015','EPS_in_Rs_2016','EPS_in_Rs_2017',
            'EPS_in_Rs_2014_YoY','EPS_in_Rs_2015_YoY','EPS_in_Rs_2016_YoY','EPS_in_Rs_2017_YoY',
            'Tax__2013','Tax__2014','Tax__2015','Tax__2016','Tax__2017',
            'Tax__2014_YoY','Tax__2015_YoY','Tax__2016_YoY','Tax__2017_YoY',
            'OPM__2013','OPM__2014','OPM__2015','OPM__2016','OPM__2017',
            'OPM__2014_YoY','OPM__2015_YoY','OPM__2016_YoY','OPM__2017_YoY',
            'Other_Assets_2013','Other_Assets_2014','Other_Assets_2015','Other_Assets_2016','Other_Assets_2017',
            'Other_Assets_2014_YoY','Other_Assets_2015_YoY','Other_Assets_2016_YoY','Other_Assets_2017_YoY',
            'Total_Liabilities_2013','Total_Liabilities_2014','Total_Liabilities_2015','Total_Liabilities_2016','Total_Liabilities_2017',
            'Total_Liabilities_2014_YoY','Total_Liabilities_2015_YoY','Total_Liabilities_2016_YoY','Total_Liabilities_2017_YoY',
            'Share_Capital_2013','Share_Capital_2014','Share_Capital_2015','Share_Capital_2016','Share_Capital_2017',
            'Share_Capital_2014_YoY','Share_Capital_2015_YoY','Share_Capital_2016_YoY','Share_Capital_2017_YoY',
            'Investments_2013','Investments_2014','Investments_2015','Investments_2016','Investments_2017',
            'Investments_2014_YoY','Investments_2015_YoY','Investments_2016_YoY','Investments_2017_YoY',
            'Borrowings_2013','Borrowings_2014','Borrowings_2015','Borrowings_2016','Borrowings_2017',
            'Borrowings_2014_YoY','Borrowings_2015_YoY','Borrowings_2016_YoY','Borrowings_2017_YoY',
            'Reserves_2013','Reserves_2014','Reserves_2015','Reserves_2016','Reserves_2017',
            'Reserves_2014_YoY','Reserves_2015_YoY','Reserves_2016_YoY','Reserves_2017_YoY',
            'Total_Assets_2013','Total_Assets_2014','Total_Assets_2015','Total_Assets_2016','Total_Assets_2017',
            'Total_Assets_2014_YoY','Total_Assets_2015_YoY','Total_Assets_2016_YoY','Total_Assets_2017_YoY',
            'Fixed_Assets_2013','Fixed_Assets_2014','Fixed_Assets_2015','Fixed_Assets_2016','Fixed_Assets_2017',
            'Fixed_Assets_2014_YoY','Fixed_Assets_2015_YoY','Fixed_Assets_2016_YoY','Fixed_Assets_2017_YoY',
            'Other_Liabilities_2013','Other_Liabilities_2014','Other_Liabilities_2015','Other_Liabilities_2016','Other_Liabilities_2017',
            'Other_Liabilities_2014_YoY','Other_Liabilities_2015_YoY','Other_Liabilities_2016_YoY','Other_Liabilities_2017_YoY',
            'CWIP_2013','CWIP_2014','CWIP_2015','CWIP_2016','CWIP_2017',
            'CWIP_2014_YoY','CWIP_2015_YoY','CWIP_2016_YoY','CWIP_2017_YoY',
            'Cash_from_Investing_Activity_2013','Cash_from_Investing_Activity_2014','Cash_from_Investing_Activity_2015','Cash_from_Investing_Activity_2016','Cash_from_Investing_Activity_2017',
            'Cash_from_Investing_Activity_2014_YoY','Cash_from_Investing_Activity_2015_YoY','Cash_from_Investing_Activity_2016_YoY','Cash_from_Investing_Activity_2017_YoY',
            'Cash_from_Operating_Activity_2013','Cash_from_Operating_Activity_2014','Cash_from_Operating_Activity_2015','Cash_from_Operating_Activity_2016','Cash_from_Operating_Activity_2017',
            'Cash_from_Operating_Activity_2014_YoY','Cash_from_Operating_Activity_2015_YoY','Cash_from_Operating_Activity_2016_YoY','Cash_from_Operating_Activity_2017_YoY',
            'Cash_from_Financing_Activity_2013','Cash_from_Financing_Activity_2014','Cash_from_Financing_Activity_2015','Cash_from_Financing_Activity_2016','Cash_from_Financing_Activity_2017',
            'Cash_from_Financing_Activity_2014_YoY','Cash_from_Financing_Activity_2015_YoY','Cash_from_Financing_Activity_2016_YoY','Cash_from_Financing_Activity_2017_YoY',
            'Net_Cash_Flow_2013','Net_Cash_Flow_2014','Net_Cash_Flow_2015','Net_Cash_Flow_2016','Net_Cash_Flow_2017',
            'Net_Cash_Flow_2014_YoY','Net_Cash_Flow_2015_YoY','Net_Cash_Flow_2016_YoY','Net_Cash_Flow_2017_YoY',
            'Share_Capital_%_2013','Share_Capital_%_2014','Share_Capital_%_2015','Share_Capital_%_2016','Share_Capital_%_2017',
            'Reserves_%_2013','Reserves_%_2014','Reserves_%_2015','Reserves_%_2016','Reserves_%_2017',
            'Borrowings_%_2013','Borrowings_%_2014','Borrowings_%_2015','Borrowings_%_2016','Borrowings_%_2017',
            'Other_Liabilities_%_2013','Other_Liabilities_%_2014','Other_Liabilities_%_2015','Other_Liabilities_%_2016','Other_Liabilities_%_2017',
            'Fixed_Assets_%_2013','Fixed_Assets_%_2014','Fixed_Assets_%_2015','Fixed_Assets_%_2016','Fixed_Assets_%_2017',
            'CWIP_%_2013','CWIP_%_2014','CWIP_%_2015','CWIP_%_2016','CWIP_%_2017',
            'Investments_%_2013','Investments_%_2014','Investments_%_2015','Investments_%_2016','Investments_%_2017',
            'Other_Assets_%_2013','Other_Assets_%_2014','Other_Assets_%_2015','Other_Assets_%_2016','Other_Assets_%_2017',
            'MarketCap','CapFlag','LageCap','MidCap','SmallCap','TinyCap','Industry',
            '2017_01_CLOSE','2017_02_CLOSE','2017_03_CLOSE','2017_04_CLOSE','2017_05_CLOSE','2017_06_CLOSE','2017_07_CLOSE','2017_08_CLOSE','2017_09_CLOSE','2017_10_CLOSE','2017_11_CLOSE','2017_12_CLOSE',
            '2018']


list_2019 = ['Tikr',
            'Sales_2014','Sales_2015','Sales_2016','Sales_2017','Sales_2018',
            'Sales_2015_YoY','Sales_2016_YoY','Sales_2017_YoY','Sales_2018_YoY',
            'Revenue_2014','Revenue_2015','Revenue_2016','Revenue_2017','Revenue_2018',
            'Revenue_2015_YoY','Revenue_2016_YoY','Revenue_2017_YoY','Revenue_2018_YoY',
            'Expenses_2014','Expenses_2015','Expenses_2016','Expenses_2017','Expenses_2018',
            'Expenses_2015_YoY','Expenses_2016_YoY','Expenses_2017_YoY','Expenses_2018_YoY',
            'Net_Profit_2014','Net_Profit_2015','Net_Profit_2016','Net_Profit_2017','Net_Profit_2018',
            'Net_Profit_2015_YoY','Net_Profit_2016_YoY','Net_Profit_2017_YoY','Net_Profit_2018_YoY',
            'Operating_Profit_2014','Operating_Profit_2015','Operating_Profit_2016','Operating_Profit_2017','Operating_Profit_2018',
            'Operating_Profit_2015_YoY','Operating_Profit_2016_YoY','Operating_Profit_2017_YoY','Operating_Profit_2018_YoY',
            'EPS_in_Rs_2014','EPS_in_Rs_2015','EPS_in_Rs_2016','EPS_in_Rs_2017','EPS_in_Rs_2018',
            'EPS_in_Rs_2015_YoY','EPS_in_Rs_2016_YoY','EPS_in_Rs_2017_YoY','EPS_in_Rs_2018_YoY',
            'Tax__2014','Tax__2015','Tax__2016','Tax__2017','Tax__2018',
            'Tax__2015_YoY','Tax__2016_YoY','Tax__2017_YoY','Tax__2018_YoY',
            'OPM__2014','OPM__2015','OPM__2016','OPM__2017','OPM__2018',
            'OPM__2015_YoY','OPM__2016_YoY','OPM__2017_YoY','OPM__2018_YoY',
            'Other_Assets_2014','Other_Assets_2015','Other_Assets_2016','Other_Assets_2017','Other_Assets_2018',
            'Other_Assets_2015_YoY','Other_Assets_2016_YoY','Other_Assets_2017_YoY','Other_Assets_2018_YoY',
            'Total_Liabilities_2014','Total_Liabilities_2015','Total_Liabilities_2016','Total_Liabilities_2017','Total_Liabilities_2018',
            'Total_Liabilities_2015_YoY','Total_Liabilities_2016_YoY','Total_Liabilities_2017_YoY','Total_Liabilities_2018_YoY',
            'Share_Capital_2014','Share_Capital_2015','Share_Capital_2016','Share_Capital_2017','Share_Capital_2018',
            'Share_Capital_2015_YoY','Share_Capital_2016_YoY','Share_Capital_2017_YoY','Share_Capital_2018_YoY',
            'Investments_2014','Investments_2015','Investments_2016','Investments_2017','Investments_2018',
            'Investments_2015_YoY','Investments_2016_YoY','Investments_2017_YoY','Investments_2018_YoY',
            'Borrowings_2014','Borrowings_2015','Borrowings_2016','Borrowings_2017','Borrowings_2018',
            'Borrowings_2015_YoY','Borrowings_2016_YoY','Borrowings_2017_YoY','Borrowings_2018_YoY',
            'Reserves_2014','Reserves_2015','Reserves_2016','Reserves_2017','Reserves_2018',
            'Reserves_2015_YoY','Reserves_2016_YoY','Reserves_2017_YoY','Reserves_2018_YoY',
            'Total_Assets_2014','Total_Assets_2015','Total_Assets_2016','Total_Assets_2017','Total_Assets_2018',
            'Total_Assets_2015_YoY','Total_Assets_2016_YoY','Total_Assets_2017_YoY','Total_Assets_2018_YoY',
            'Fixed_Assets_2014','Fixed_Assets_2015','Fixed_Assets_2016','Fixed_Assets_2017','Fixed_Assets_2018',
            'Fixed_Assets_2015_YoY','Fixed_Assets_2016_YoY','Fixed_Assets_2017_YoY','Fixed_Assets_2018_YoY',
            'Other_Liabilities_2014','Other_Liabilities_2015','Other_Liabilities_2016','Other_Liabilities_2017','Other_Liabilities_2018',
            'Other_Liabilities_2015_YoY','Other_Liabilities_2016_YoY','Other_Liabilities_2017_YoY','Other_Liabilities_2018_YoY',
            'CWIP_2014','CWIP_2015','CWIP_2016','CWIP_2017','CWIP_2018',
            'CWIP_2015_YoY','CWIP_2016_YoY','CWIP_2017_YoY','CWIP_2018_YoY',
            'Cash_from_Investing_Activity_2014','Cash_from_Investing_Activity_2015','Cash_from_Investing_Activity_2016','Cash_from_Investing_Activity_2017','Cash_from_Investing_Activity_2018',
            'Cash_from_Investing_Activity_2015_YoY','Cash_from_Investing_Activity_2016_YoY','Cash_from_Investing_Activity_2017_YoY','Cash_from_Investing_Activity_2018_YoY',
            'Cash_from_Operating_Activity_2014','Cash_from_Operating_Activity_2015','Cash_from_Operating_Activity_2016','Cash_from_Operating_Activity_2017','Cash_from_Operating_Activity_2018',
            'Cash_from_Operating_Activity_2015_YoY','Cash_from_Operating_Activity_2016_YoY','Cash_from_Operating_Activity_2017_YoY','Cash_from_Operating_Activity_2018_YoY',
            'Cash_from_Financing_Activity_2014','Cash_from_Financing_Activity_2015','Cash_from_Financing_Activity_2016','Cash_from_Financing_Activity_2017','Cash_from_Financing_Activity_2018',
            'Cash_from_Financing_Activity_2015_YoY','Cash_from_Financing_Activity_2016_YoY','Cash_from_Financing_Activity_2017_YoY','Cash_from_Financing_Activity_2018_YoY',
            'Net_Cash_Flow_2014','Net_Cash_Flow_2015','Net_Cash_Flow_2016','Net_Cash_Flow_2017','Net_Cash_Flow_2018',
            'Net_Cash_Flow_2015_YoY','Net_Cash_Flow_2016_YoY','Net_Cash_Flow_2017_YoY','Net_Cash_Flow_2018_YoY',
            'Share_Capital_%_2014','Share_Capital_%_2015','Share_Capital_%_2016','Share_Capital_%_2017','Share_Capital_%_2018',
            'Reserves_%_2014','Reserves_%_2015','Reserves_%_2016','Reserves_%_2017','Reserves_%_2018',
            'Borrowings_%_2014','Borrowings_%_2015','Borrowings_%_2016','Borrowings_%_2017','Borrowings_%_2018',
            'Other_Liabilities_%_2014','Other_Liabilities_%_2015','Other_Liabilities_%_2016','Other_Liabilities_%_2017','Other_Liabilities_%_2018',
            'Fixed_Assets_%_2014','Fixed_Assets_%_2015','Fixed_Assets_%_2016','Fixed_Assets_%_2017','Fixed_Assets_%_2018',
            'CWIP_%_2014','CWIP_%_2015','CWIP_%_2016','CWIP_%_2017','CWIP_%_2018',
            'Investments_%_2014','Investments_%_2015','Investments_%_2016','Investments_%_2017','Investments_%_2018',
            'Other_Assets_%_2014','Other_Assets_%_2015','Other_Assets_%_2016','Other_Assets_%_2017','Other_Assets_%_2018',
            'MarketCap','CapFlag','LageCap','MidCap','SmallCap','TinyCap','Industry',
            '2018_01_CLOSE','2018_02_CLOSE','2018_03_CLOSE','2018_04_CLOSE','2018_05_CLOSE','2018_06_CLOSE','2018_07_CLOSE','2018_08_CLOSE','2018_09_CLOSE','2018_10_CLOSE','2018_11_CLOSE','2018_12_CLOSE',
            '2019']

# list_2020 = ['Tikr',        
#             'Sales_2015','Sales_2016','Sales_2017','Sales_2018','Sales_2019',
#             'Sales_2016_YoY','Sales_2017_YoY','Sales_2018_YoY','Sales_2019_YoY',
#             'Revenue_2015','Revenue_2016','Revenue_2017','Revenue_2018','Revenue_2019',
#             'Revenue_2016_YoY','Revenue_2017_YoY','Revenue_2018_YoY','Revenue_2019_YoY',
#             'Expenses_2015','Expenses_2016','Expenses_2017','Expenses_2018','Expenses_2019',
#             'Expenses_2016_YoY','Expenses_2017_YoY','Expenses_2018_YoY','Expenses_2019_YoY',
#             'Net_Profit_2015','Net_Profit_2016','Net_Profit_2017','Net_Profit_2018','Net_Profit_2019',
#             'Net_Profit_2016_YoY','Net_Profit_2017_YoY','Net_Profit_2018_YoY','Net_Profit_2019_YoY',
#             'Operating_Profit_2015','Operating_Profit_2016','Operating_Profit_2017','Operating_Profit_2018','Operating_Profit_2019',
#             'Operating_Profit_2016_YoY','Operating_Profit_2017_YoY','Operating_Profit_2018_YoY','Operating_Profit_2019_YoY',
#             'EPS_in_Rs_2015','EPS_in_Rs_2016','EPS_in_Rs_2017','EPS_in_Rs_2018','EPS_in_Rs_2019',
#             'EPS_in_Rs_2016_YoY','EPS_in_Rs_2017_YoY','EPS_in_Rs_2018_YoY','EPS_in_Rs_2019_YoY',
#             'Tax__2015','Tax__2016','Tax__2017','Tax__2018','Tax__2019',
#             'Tax__2016_YoY','Tax__2017_YoY','Tax__2018_YoY','Tax__2019_YoY',
#             'OPM__2015','OPM__2016','OPM__2017','OPM__2018','OPM__2019',
#             'OPM__2016_YoY','OPM__2017_YoY','OPM__2018_YoY','OPM__2019_YoY',
#             'Other_Assets_2015','Other_Assets_2016','Other_Assets_2017','Other_Assets_2018','Other_Assets_2019',
#             'Other_Assets_2016_YoY','Other_Assets_2017_YoY','Other_Assets_2018_YoY','Other_Assets_2019_YoY',
#             'Total_Liabilities_2015','Total_Liabilities_2016','Total_Liabilities_2017','Total_Liabilities_2018','Total_Liabilities_2019',
#             'Total_Liabilities_2016_YoY','Total_Liabilities_2017_YoY','Total_Liabilities_2018_YoY','Total_Liabilities_2019_YoY',
#             'Share_Capital_2015','Share_Capital_2016','Share_Capital_2017','Share_Capital_2018','Share_Capital_2019',
#             'Share_Capital_2016_YoY','Share_Capital_2017_YoY','Share_Capital_2018_YoY','Share_Capital_2019_YoY',
#             'Investments_2015','Investments_2016','Investments_2017','Investments_2018','Investments_2019',
#             'Investments_2016_YoY','Investments_2017_YoY','Investments_2018_YoY','Investments_2019_YoY',
#             'Borrowings_2015','Borrowings_2016','Borrowings_2017','Borrowings_2018','Borrowings_2019',
#             'Borrowings_2016_YoY','Borrowings_2017_YoY','Borrowings_2018_YoY','Borrowings_2019_YoY',
#             'Reserves_2015','Reserves_2016','Reserves_2017','Reserves_2018','Reserves_2019',
#             'Reserves_2016_YoY','Reserves_2017_YoY','Reserves_2018_YoY','Reserves_2019_YoY',
#             'Total_Assets_2015','Total_Assets_2016','Total_Assets_2017','Total_Assets_2018','Total_Assets_2019',
#             'Total_Assets_2016_YoY','Total_Assets_2017_YoY','Total_Assets_2018_YoY','Total_Assets_2019_YoY',
#             'Fixed_Assets_2015','Fixed_Assets_2016','Fixed_Assets_2017','Fixed_Assets_2018','Fixed_Assets_2019',
#             'Fixed_Assets_2016_YoY','Fixed_Assets_2017_YoY','Fixed_Assets_2018_YoY','Fixed_Assets_2019_YoY',
#             'Other_Liabilities_2015','Other_Liabilities_2016','Other_Liabilities_2017','Other_Liabilities_2018','Other_Liabilities_2019',
#             'Other_Liabilities_2016_YoY','Other_Liabilities_2017_YoY','Other_Liabilities_2018_YoY','Other_Liabilities_2019_YoY',
#             'CWIP_2015','CWIP_2016','CWIP_2017','CWIP_2018','CWIP_2019',
#             'CWIP_2016_YoY','CWIP_2017_YoY','CWIP_2018_YoY','CWIP_2019_YoY',
#             'Cash_from_Investing_Activity_2015','Cash_from_Investing_Activity_2016','Cash_from_Investing_Activity_2017','Cash_from_Investing_Activity_2018','Cash_from_Investing_Activity_2019',
#             'Cash_from_Investing_Activity_2016_YoY','Cash_from_Investing_Activity_2017_YoY','Cash_from_Investing_Activity_2018_YoY','Cash_from_Investing_Activity_2019_YoY',
#             'Cash_from_Operating_Activity_2015','Cash_from_Operating_Activity_2016','Cash_from_Operating_Activity_2017','Cash_from_Operating_Activity_2018','Cash_from_Operating_Activity_2019',
#             'Cash_from_Operating_Activity_2016_YoY','Cash_from_Operating_Activity_2017_YoY','Cash_from_Operating_Activity_2018_YoY','Cash_from_Operating_Activity_2019_YoY',
#             'Cash_from_Financing_Activity_2015','Cash_from_Financing_Activity_2016','Cash_from_Financing_Activity_2017','Cash_from_Financing_Activity_2018','Cash_from_Financing_Activity_2019',
#             'Cash_from_Financing_Activity_2016_YoY','Cash_from_Financing_Activity_2017_YoY','Cash_from_Financing_Activity_2018_YoY','Cash_from_Financing_Activity_2019_YoY',
#             'Net_Cash_Flow_2015','Net_Cash_Flow_2016','Net_Cash_Flow_2017','Net_Cash_Flow_2018','Net_Cash_Flow_2019',
#             'Net_Cash_Flow_2016_YoY','Net_Cash_Flow_2017_YoY','Net_Cash_Flow_2018_YoY','Net_Cash_Flow_2019_YoY',
#             'Share_Capital_%_2015','Share_Capital_%_2016','Share_Capital_%_2017','Share_Capital_%_2018','Share_Capital_%_2019',
#             'Reserves_%_2015','Reserves_%_2016','Reserves_%_2017','Reserves_%_2018','Reserves_%_2019',
#             'Borrowings_%_2015','Borrowings_%_2016','Borrowings_%_2017','Borrowings_%_2018','Borrowings_%_2019',
#             'Other_Liabilities_%_2015','Other_Liabilities_%_2016','Other_Liabilities_%_2017','Other_Liabilities_%_2018','Other_Liabilities_%_2019',
#             'Fixed_Assets_%_2015','Fixed_Assets_%_2016','Fixed_Assets_%_2017','Fixed_Assets_%_2018','Fixed_Assets_%_2019',
#             'CWIP_%_2015','CWIP_%_2016','CWIP_%_2017','CWIP_%_2018','CWIP_%_2019',
#             'Investments_%_2015','Investments_%_2016','Investments_%_2017','Investments_%_2018','Investments_%_2019',
#             'Other_Assets_%_2015','Other_Assets_%_2016','Other_Assets_%_2017','Other_Assets_%_2018','Other_Assets_%_2019',
#             'MarketCap','CapFlag','LageCap','MidCap','SmallCap','TinyCap','Industry',
#             '2019_01_CLOSE','2019_02_CLOSE','2019_03_CLOSE','2019_04_CLOSE','2019_05_CLOSE','2019_06_CLOSE','2019_07_CLOSE','2019_08_CLOSE','2019_09_CLOSE','2019_10_CLOSE','2019_11_CLOSE','2019_12_CLOSE',
#             '2020']

# list_2021 = ['Tikr',
#             'Sales_2016','Sales_2017','Sales_2018','Sales_2019','Sales_2020',
#             'Sales_2017_YoY','Sales_2018_YoY','Sales_2019_YoY','Sales_2020_YoY',
#             'Revenue_2016','Revenue_2017','Revenue_2018','Revenue_2019','Revenue_2020',
#             'Revenue_2017_YoY','Revenue_2018_YoY','Revenue_2019_YoY','Revenue_2020_YoY',
#             'Expenses_2016','Expenses_2017','Expenses_2018','Expenses_2019','Expenses_2020',
#             'Expenses_2017_YoY','Expenses_2018_YoY','Expenses_2019_YoY','Expenses_2020_YoY',
#             'Net_Profit_2016','Net_Profit_2017','Net_Profit_2018','Net_Profit_2019','Net_Profit_2020',
#             'Net_Profit_2017_YoY','Net_Profit_2018_YoY','Net_Profit_2019_YoY','Net_Profit_2020_YoY',
#             'Operating_Profit_2016','Operating_Profit_2017','Operating_Profit_2018','Operating_Profit_2019','Operating_Profit_2020',
#             'Operating_Profit_2017_YoY','Operating_Profit_2018_YoY','Operating_Profit_2019_YoY','Operating_Profit_2020_YoY',
#             'EPS_in_Rs_2016','EPS_in_Rs_2017','EPS_in_Rs_2018','EPS_in_Rs_2019','EPS_in_Rs_2020',
#             'EPS_in_Rs_2017_YoY','EPS_in_Rs_2018_YoY','EPS_in_Rs_2019_YoY','EPS_in_Rs_2020_YoY',
#             'Tax__2016','Tax__2017','Tax__2018','Tax__2019','Tax__2020',
#             'Tax__2017_YoY','Tax__2018_YoY','Tax__2019_YoY','Tax__2020_YoY',
#             'OPM__2016','OPM__2017','OPM__2018','OPM__2019','OPM__2020',
#             'OPM__2017_YoY','OPM__2018_YoY','OPM__2019_YoY','OPM__2020_YoY',
#             'Other_Assets_2016','Other_Assets_2017','Other_Assets_2018','Other_Assets_2019','Other_Assets_2020',
#             'Other_Assets_2017_YoY','Other_Assets_2018_YoY','Other_Assets_2019_YoY','Other_Assets_2020_YoY',
#             'Total_Liabilities_2016','Total_Liabilities_2017','Total_Liabilities_2018','Total_Liabilities_2019','Total_Liabilities_2020',
#             'Total_Liabilities_2017_YoY','Total_Liabilities_2018_YoY','Total_Liabilities_2019_YoY','Total_Liabilities_2020_YoY',
#             'Share_Capital_2016','Share_Capital_2017','Share_Capital_2018','Share_Capital_2019','Share_Capital_2020',
#             'Share_Capital_2017_YoY','Share_Capital_2018_YoY','Share_Capital_2019_YoY','Share_Capital_2020_YoY',
#             'Investments_2016','Investments_2017','Investments_2018','Investments_2019','Investments_2020',
#             'Investments_2017_YoY','Investments_2018_YoY','Investments_2019_YoY','Investments_2020_YoY',
#             'Borrowings_2016','Borrowings_2017','Borrowings_2018','Borrowings_2019','Borrowings_2020',
#             'Borrowings_2017_YoY','Borrowings_2018_YoY','Borrowings_2019_YoY','Borrowings_2020_YoY',
#             'Reserves_2016','Reserves_2017','Reserves_2018','Reserves_2019','Reserves_2020',
#             'Reserves_2017_YoY','Reserves_2018_YoY','Reserves_2019_YoY','Reserves_2020_YoY',
#             'Total_Assets_2016','Total_Assets_2017','Total_Assets_2018','Total_Assets_2019','Total_Assets_2020',
#             'Total_Assets_2017_YoY','Total_Assets_2018_YoY','Total_Assets_2019_YoY','Total_Assets_2020_YoY',
#             'Fixed_Assets_2016','Fixed_Assets_2017','Fixed_Assets_2018','Fixed_Assets_2019','Fixed_Assets_2020',
#             'Fixed_Assets_2017_YoY','Fixed_Assets_2018_YoY','Fixed_Assets_2019_YoY','Fixed_Assets_2020_YoY',
#             'Other_Liabilities_2016','Other_Liabilities_2017','Other_Liabilities_2018','Other_Liabilities_2019','Other_Liabilities_2020',
#             'Other_Liabilities_2017_YoY','Other_Liabilities_2018_YoY','Other_Liabilities_2019_YoY','Other_Liabilities_2020_YoY',
#             'CWIP_2016','CWIP_2017','CWIP_2018','CWIP_2019','CWIP_2020',
#             'CWIP_2017_YoY','CWIP_2018_YoY','CWIP_2019_YoY','CWIP_2020_YoY',
#             'Cash_from_Investing_Activity_2016','Cash_from_Investing_Activity_2017','Cash_from_Investing_Activity_2018','Cash_from_Investing_Activity_2019','Cash_from_Investing_Activity_2020',
#             'Cash_from_Investing_Activity_2017_YoY','Cash_from_Investing_Activity_2018_YoY','Cash_from_Investing_Activity_2019_YoY','Cash_from_Investing_Activity_2020_YoY',
#             'Cash_from_Operating_Activity_2016','Cash_from_Operating_Activity_2017','Cash_from_Operating_Activity_2018','Cash_from_Operating_Activity_2019','Cash_from_Operating_Activity_2020',
#             'Cash_from_Operating_Activity_2017_YoY','Cash_from_Operating_Activity_2018_YoY','Cash_from_Operating_Activity_2019_YoY','Cash_from_Operating_Activity_2020_YoY',
#             'Cash_from_Financing_Activity_2016','Cash_from_Financing_Activity_2017','Cash_from_Financing_Activity_2018','Cash_from_Financing_Activity_2019','Cash_from_Financing_Activity_2020',
#             'Cash_from_Financing_Activity_2017_YoY','Cash_from_Financing_Activity_2018_YoY','Cash_from_Financing_Activity_2019_YoY','Cash_from_Financing_Activity_2020_YoY',
#             'Net_Cash_Flow_2016','Net_Cash_Flow_2017','Net_Cash_Flow_2018','Net_Cash_Flow_2019','Net_Cash_Flow_2020',
#             'Net_Cash_Flow_2017_YoY','Net_Cash_Flow_2018_YoY','Net_Cash_Flow_2019_YoY','Net_Cash_Flow_2020_YoY',
#             'Share_Capital_%_2016','Share_Capital_%_2017','Share_Capital_%_2018','Share_Capital_%_2019','Share_Capital_%_2020',
#             'Reserves_%_2016','Reserves_%_2017','Reserves_%_2018','Reserves_%_2019','Reserves_%_2020',
#             'Borrowings_%_2016','Borrowings_%_2017','Borrowings_%_2018','Borrowings_%_2019','Borrowings_%_2020',
#             'Other_Liabilities_%_2016','Other_Liabilities_%_2017','Other_Liabilities_%_2018','Other_Liabilities_%_2019','Other_Liabilities_%_2020',
#             'Fixed_Assets_%_2016','Fixed_Assets_%_2017','Fixed_Assets_%_2018','Fixed_Assets_%_2019','Fixed_Assets_%_2020',
#             'CWIP_%_2016','CWIP_%_2017','CWIP_%_2018','CWIP_%_2019','CWIP_%_2020',
#             'Investments_%_2016','Investments_%_2017','Investments_%_2018','Investments_%_2019','Investments_%_2020',
#             'Other_Assets_%_2016','Other_Assets_%_2017','Other_Assets_%_2018','Other_Assets_%_2019','Other_Assets_%_2020',
#             'MarketCap','CapFlag','LageCap','MidCap','SmallCap','TinyCap','Industry',
#             '2020_01_CLOSE','2020_02_CLOSE','2020_03_CLOSE','2020_04_CLOSE','2020_05_CLOSE','2020_06_CLOSE','2020_07_CLOSE','2020_08_CLOSE','2020_09_CLOSE','2020_10_CLOSE','2020_11_CLOSE','2020_12_CLOSE',
#             '2021']

# df_2013 = df_merge[list_2013]
# df_2013['Year'] = '2013'
# df_2014 = df_merge[list_2014]
# df_2014['Year'] = '2014'
df_2015 = df_merge[list_2015]
df_2015['Year'] = '2015'
df_2016 = df_merge[list_2016]
df_2016['Year'] = '2016'
df_2017 = df_merge[list_2017]
df_2017['Year'] = '2017'
df_2018 = df_merge[list_2018]
df_2018['Year'] = '2018'
df_2019 = df_merge[list_2019]
df_2019['Year'] = '2019'
# df_2020 = df_merge[list_2020]
# df_2020['Year'] = '2020'
# df_2021 = df_merge[list_2021]
# df_2021['Year'] = '2021'

col_names = ['Tikr','Sales_yr_1','Sales_yr_2','Sales_yr_3','Sales_yr_4','Sales_yr_5',
            'Sales_yr_2_YoY','Sales_yr_3_YoY','Sales_yr_4_YoY','Sales_yr_5_YoY',
            'Revenue_yr_1','Revenue_yr_2','Revenue_yr_3','Revenue_yr_4','Revenue_yr_5',
            'Revenue_yr_2_YoY','Revenue_yr_3_YoY','Revenue_yr_4_YoY','Revenue_yr_5_YoY',
            'Expenses_yr_1','Expenses_yr_2','Expenses_yr_3','Expenses_yr_4','Expenses_yr_5',
            'Expenses_yr_2_YoY','Expenses_yr_3_YoY','Expenses_yr_4_YoY','Expenses_yr_5_YoY',
            'Net_Profit_yr_1','Net_Profit_yr_2','Net_Profit_yr_3','Net_Profit_yr_4','Net_Profit_yr_5',
            'Net_Profit_yr_2_YoY','Net_Profit_yr_3_YoY','Net_Profit_yr_4_YoY','Net_Profit_yr_5_YoY',
            'Operating_Profit_yr_1','Operating_Profit_yr_2','Operating_Profit_yr_3','Operating_Profit_yr_4','Operating_Profit_yr_5',
            'Operating_Profit_yr_2_YoY','Operating_Profit_yr_3_YoY','Operating_Profit_yr_4_YoY','Operating_Profit_yr_5_YoY',
            'EPS_in_Rs_yr_1','EPS_in_Rs_yr_2','EPS_in_Rs_yr_3','EPS_in_Rs_yr_4','EPS_in_Rs_yr_5',
            'EPS_in_Rs_yr_2_YoY','EPS_in_Rs_yr_3_YoY','EPS_in_Rs_yr_4_YoY','EPS_in_Rs_yr_5_YoY',
            'Tax__yr_1','Tax__yr_2','Tax__yr_3','Tax__yr_4','Tax__yr_5',
            'Tax__yr_2_YoY','Tax__yr_3_YoY','Tax__yr_4_YoY','Tax__yr_5_YoY',
            'OPM__yr_1','OPM__yr_2','OPM__yr_3','OPM__yr_4','OPM__yr_5',
            'OPM__yr_2_YoY','OPM__yr_3_YoY','OPM__yr_4_YoY','OPM__yr_5_YoY',
            'Other_Assets_yr_1','Other_Assets_yr_2','Other_Assets_yr_3','Other_Assets_yr_4','Other_Assets_yr_5',
            'Other_Assets_yr_2_YoY','Other_Assets_yr_3_YoY','Other_Assets_yr_4_YoY','Other_Assets_yr_5_YoY',
            'Total_Liabilities_yr_1','Total_Liabilities_yr_2','Total_Liabilities_yr_3','Total_Liabilities_yr_4','Total_Liabilities_yr_5',
            'Total_Liabilities_yr_2_YoY','Total_Liabilities_yr_3_YoY','Total_Liabilities_yr_4_YoY','Total_Liabilities_yr_5_YoY',
            'Share_Capital_yr_1','Share_Capital_yr_2','Share_Capital_yr_3','Share_Capital_yr_4','Share_Capital_yr_5',
            'Share_Capital_yr_2_YoY','Share_Capital_yr_3_YoY','Share_Capital_yr_4_YoY','Share_Capital_yr_5_YoY',
            'Investments_yr_1','Investments_yr_2','Investments_yr_3','Investments_yr_4','Investments_yr_5',
            'Investments_yr_2_YoY','Investments_yr_3_YoY','Investments_yr_4_YoY','Investments_yr_5_YoY',
            'Borrowings_yr_1','Borrowings_yr_2','Borrowings_yr_3','Borrowings_yr_4','Borrowings_yr_5',
            'Borrowings_yr_2_YoY','Borrowings_yr_3_YoY','Borrowings_yr_4_YoY','Borrowings_yr_5_YoY',
            'Reserves_yr_1','Reserves_yr_2','Reserves_yr_3','Reserves_yr_4','Reserves_yr_5',
            'Reserves_yr_2_YoY','Reserves_yr_3_YoY','Reserves_yr_4_YoY','Reserves_yr_5_YoY',
            'Total_Assets_yr_1','Total_Assets_yr_2','Total_Assets_yr_3','Total_Assets_yr_4','Total_Assets_yr_5',
            'Total_Assets_yr_2_YoY','Total_Assets_yr_3_YoY','Total_Assets_yr_4_YoY','Total_Assets_yr_5_YoY',
            'Fixed_Assets_yr_1','Fixed_Assets_yr_2','Fixed_Assets_yr_3','Fixed_Assets_yr_4','Fixed_Assets_yr_5',
            'Fixed_Assets_yr_2_YoY','Fixed_Assets_yr_3_YoY','Fixed_Assets_yr_4_YoY','Fixed_Assets_yr_5_YoY',
            'Other_Liabilities_yr_1','Other_Liabilities_yr_2','Other_Liabilities_yr_3','Other_Liabilities_yr_4','Other_Liabilities_yr_5',
            'Other_Liabilities_yr_2_YoY','Other_Liabilities_yr_3_YoY','Other_Liabilities_yr_4_YoY','Other_Liabilities_yr_5_YoY',
            'CWIP_yr_1','CWIP_yr_2','CWIP_yr_3','CWIP_yr_4','CWIP_yr_5',
            'CWIP_yr_2_YoY','CWIP_yr_3_YoY','CWIP_yr_4_YoY','CWIP_yr_5_YoY',
            'Cash_from_Investing_Activity_yr_1','Cash_from_Investing_Activity_yr_2','Cash_from_Investing_Activity_yr_3','Cash_from_Investing_Activity_yr_4','Cash_from_Investing_Activity_yr_5',
            'Cash_from_Investing_Activity_yr_2_YoY','Cash_from_Investing_Activity_yr_3_YoY','Cash_from_Investing_Activity_yr_4_YoY','Cash_from_Investing_Activity_yr_5_YoY',
            'Cash_from_Operating_Activity_yr_1','Cash_from_Operating_Activity_yr_2','Cash_from_Operating_Activity_yr_3','Cash_from_Operating_Activity_yr_4','Cash_from_Operating_Activity_yr_5',
            'Cash_from_Operating_Activity_yr_2_YoY','Cash_from_Operating_Activity_yr_3_YoY','Cash_from_Operating_Activity_yr_4_YoY','Cash_from_Operating_Activity_yr_5_YoY',
            'Cash_from_Financing_Activity_yr_1','Cash_from_Financing_Activity_yr_2','Cash_from_Financing_Activity_yr_3','Cash_from_Financing_Activity_yr_4','Cash_from_Financing_Activity_yr_5',
            'Cash_from_Financing_Activity_yr_2_YoY','Cash_from_Financing_Activity_yr_3_YoY','Cash_from_Financing_Activity_yr_4_YoY','Cash_from_Financing_Activity_yr_5_YoY',
            'Net_Cash_Flow_yr_1','Net_Cash_Flow_yr_2','Net_Cash_Flow_yr_3','Net_Cash_Flow_yr_4','Net_Cash_Flow_yr_5',
            'Net_Cash_Flow_yr_2_YoY','Net_Cash_Flow_yr_3_YoY','Net_Cash_Flow_yr_4_YoY','Net_Cash_Flow_yr_5_YoY',
            'Share_Capital_%_yr_1','Share_Capital_%_yr_2','Share_Capital_%_yr_3','Share_Capital_%_yr_4','Share_Capital_%_yr_5',
            'Reserves_%_yr_1','Reserves_%_yr_2','Reserves_%_yr_3','Reserves_%_yr_4','Reserves_%_yr_5',
            'Borrowings_%_yr_1','Borrowings_%_yr_2','Borrowings_%_yr_3','Borrowings_%_yr_4','Borrowings_%_yr_5',
            'Other_Liabilities_%_yr_1','Other_Liabilities_%_yr_2','Other_Liabilities_%_yr_3','Other_Liabilities_%_yr_4','Other_Liabilities_%_yr_5',
            'Fixed_Assets_%_yr_1','Fixed_Assets_%_yr_2','Fixed_Assets_%_yr_3','Fixed_Assets_%_yr_4','Fixed_Assets_%_yr_5',
            'CWIP_%_yr_1','CWIP_%_yr_2','CWIP_%_yr_3','CWIP_%_yr_4','CWIP_%_yr_5',
            'Investments_%_yr_1','Investments_%_yr_2','Investments_%_yr_3','Investments_%_yr_4','Investments_%_yr_5',
            'Other_Assets_%_yr_1','Other_Assets_%_yr_2','Other_Assets_%_yr_3','Other_Assets_%_yr_4','Other_Assets_%_yr_5',
            'MarketCap','CapFlag','LageCap','MidCap','SmallCap','TinyCap','Industry',
            'Trend_lag_01','Trend_lag_02','Trend_lag_03','Trend_lag_04','Trend_lag_05','Trend_lag_06','Trend_lag_07','Trend_lag_08','Trend_lag_09','Trend_lag_10','Trend_lag_11','Trend_lag_12',
            'Return','Year']

#df_2013.columns = col_names
#df_2014.columns = col_names
df_2015.columns = col_names
df_2016.columns = col_names
df_2017.columns = col_names
df_2018.columns = col_names
df_2019.columns = col_names
# df_2020.columns = col_names
# df_2021.columns = col_names

# df_append = pd.concat([df_2015.reset_index(drop=True), df_2016.reset_index(drop=True), df_2017.reset_index(drop=True),
#                        df_2018.reset_index(drop=True), df_2019.reset_index(drop=True), df_2020.reset_index(drop=True)], axis=1)

#df_2013,
df_append = pd.concat([df_2015, df_2016, df_2017, df_2018, df_2019], ignore_index=True) #, df_2020, df_2021
#df_2020, Removed 2020 from the data purposefully in order to remove the bias that gets added due to Covid

C:\Users\hashmy\AppData\Local\Programs\Python\Python36\lib\site-packages\ipykernel_launcher.py:424: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\hashmy\AppData\Local\Programs\Python\Python36\lib\site-packages\ipykernel_launcher.py:426: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\hashmy\AppData\Local\Programs\Python\Python36\lib\site-packages\ipykernel_launcher.py:428: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\hashmy\AppData\Local\Programs\Python\Python36\lib\site-packages\ipykernel_launcher.py:430: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\hashmy\AppData\Local\Programs\Python\Python36\lib\site-packages\ipykernel_launcher.py:432: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [22]:
df_append.head()
#df_append.shape

,Tikr,Sales_yr_1,Sales_yr_2,Sales_yr_3,Sales_yr_4,Sales_yr_5,Sales_yr_2_YoY,Sales_yr_3_YoY,Sales_yr_4_YoY,Sales_yr_5_YoY,...,Trend_lag_05,Trend_lag_06,Trend_lag_07,Trend_lag_08,Trend_lag_09,Trend_lag_10,Trend_lag_11,Trend_lag_12,Return,Year
0,20MICRONS,175.00,234.00,262.00,275.00,288.00,33.714286,11.965812,4.961832,4.727273,...,3.942376,4.245082,-8.900086,-2.150535,-0.125591,-3.175105,-0.689936,-0.809149,30.123639,2015
1,21STCENMGM,1.18,23.45,-4.20,0.12,1.08,1887.288136,-117.910448,-102.857143,800.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2015
2,3IINFOTECH,692.00,963.00,1120.00,1198.00,1278.00,39.161850,16.303219,6.964286,6.677796,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2015
3,3MINDIA,1087.00,1191.00,1405.00,1574.00,1742.00,9.567617,17.968094,12.028470,10.673443,...,8.485062,12.153120,6.193921,17.388658,10.294305,-2.990968,5.465670,-0.208745,46.426779,2015
4,3PLAND,70.27,99.43,125.64,133.58,137.98,41.497083,26.360253,6.319643,3.293906,...,3.880598,34.942525,22.018740,-10.296682,-7.003894,-9.309623,-0.230679,-4.277458,-6.210587,2015

In [ ]:
# Getting rid of revenue columns.. since it is equivalent to sales for Financial Companies
df_append['Sales_yr_1'] = df_append[['Sales_yr_1','Revenue_yr_1']].sum(axis=1)
df_append['Sales_yr_2'] = df_append[['Sales_yr_2','Revenue_yr_2']].sum(axis=1)
df_append['Sales_yr_3'] = df_append[['Sales_yr_3','Revenue_yr_3']].sum(axis=1)
df_append['Sales_yr_4'] = df_append[['Sales_yr_4','Revenue_yr_3']].sum(axis=1)
df_append['Sales_yr_5'] = df_append[['Sales_yr_5','Revenue_yr_3']].sum(axis=1)

df_append['Sales_yr_2_YoY'] = df_append[['Sales_yr_2_YoY','Revenue_yr_2_YoY']].sum(axis=1)
df_append['Sales_yr_3_YoY'] = df_append[['Sales_yr_3_YoY','Revenue_yr_3_YoY']].sum(axis=1)
df_append['Sales_yr_4_YoY'] = df_append[['Sales_yr_4_YoY','Revenue_yr_4_YoY']].sum(axis=1)
df_append['Sales_yr_5_YoY'] = df_append[['Sales_yr_5_YoY','Revenue_yr_5_YoY']].sum(axis=1)

df_append.drop(['Revenue_yr_1','Revenue_yr_2','Revenue_yr_3','Revenue_yr_4','Revenue_yr_5',
                'Revenue_yr_2_YoY','Revenue_yr_3_YoY','Revenue_yr_4_YoY','Revenue_yr_5_YoY'],axis=1,inplace=True)

In [ ]:
df_append[df_append['Tikr'] == 'RELIANCE']

,Tikr,Sales_yr_1,Sales_yr_2,Sales_yr_3,Sales_yr_4,Sales_yr_5,Sales_yr_2_YoY,Sales_yr_3_YoY,Sales_yr_4_YoY,Sales_yr_5_YoY,...,Trend_lag_05,Trend_lag_06,Trend_lag_07,Trend_lag_08,Trend_lag_09,Trend_lag_10,Trend_lag_11,Trend_lag_12,Return,Year
1180,RELIANCE,191896.0,247414.0,329083.0,359195.0,389178.0,28.931296,33.009046,9.150275,8.347277,...,13.188792,-0.526791,-6.775971,0.990761,-1.575950,-1.862563,2.450094,-8.307541,7.799354,2015
2799,RELIANCE,247414.0,329083.0,359195.0,389178.0,328013.0,33.009046,9.150275,8.347277,-15.716459,...,0.080973,8.698728,5.431941,-9.785702,-5.354072,7.144920,3.128865,3.645484,6.880935,2016
4418,RELIANCE,329083.0,359195.0,389178.0,328013.0,231743.0,9.150275,8.347277,-15.716459,-29.349447,...,-6.584058,0.622452,3.710816,1.646875,5.384470,-1.335613,-6.386799,6.237279,59.261297,2017
6037,RELIANCE,359195.0,389178.0,328013.0,231743.0,240597.0,8.347277,-15.716459,-29.349447,3.820612,...,-4.334991,3.991798,13.519311,0.900376,3.400104,10.495550,1.614689,0.690467,104.872479,2018
7656,RELIANCE,389178.0,328013.0,231743.0,240597.0,289188.0,-15.716459,-29.349447,3.820612,20.196012,...,-0.210186,5.538557,11.395436,11.719537,1.625707,-13.780157,4.031545,-0.777728,81.269160,2019
9275,RELIANCE,328013.0,231743.0,240597.0,289188.0,370744.0,-29.349447,3.820612,20.196012,28.201723,...,-5.848739,-0.395328,-4.109350,0.791316,1.836642,11.955264,6.252540,3.976057,62.554125,2020
10894,RELIANCE,231743.0,240597.0,289188.0,370744.0,336097.0,3.820612,20.196012,28.201723,-9.345262,...,11.854526,14.656118,18.699352,5.315508,7.403538,-5.253854,-8.520659,1.695133,65.483867,2021

In [ ]:
# Mapping nifty returns to subtract from 
df_bhav_return[df_bhav_return['Tikr'] == 'NIFTY50']

,2013,2014,2015,2016,2017,2018,2019,2020,2021,Tikr
Unnamed: 0,,,,,,,,,,
1577,NaN,37.611484,41.708545,10.551216,13.926248,32.721188,20.821578,0.752517,37.429123,NIFTY50

In [ ]:
df_nifty_returns = df_bhav_return[df_bhav_return['Tikr'] == 'NIFTY50']
df_nifty_melt = df_nifty_returns.melt(id_vars=["Tikr"], var_name="Year", value_name="Nifty_Returns")
df_nifty_melt

      Tikr  Year  Nifty_Returns
0  NIFTY50  2013            NaN
1  NIFTY50  2014      37.611484
2  NIFTY50  2015      41.708545
3  NIFTY50  2016      10.551216
4  NIFTY50  2017      13.926248
5  NIFTY50  2018      32.721188
6  NIFTY50  2019      20.821578
7  NIFTY50  2020       0.752517
8  NIFTY50  2021      37.429123

In [ ]:
df_final =  pd.merge(df_append,df_nifty_melt, how='left',left_on=['Year'], right_on=['Year'])
df_final.head()

,Tikr_x,Sales_yr_1,Sales_yr_2,Sales_yr_3,Sales_yr_4,Sales_yr_5,Sales_yr_2_YoY,Sales_yr_3_YoY,Sales_yr_4_YoY,Sales_yr_5_YoY,...,Trend_lag_07,Trend_lag_08,Trend_lag_09,Trend_lag_10,Trend_lag_11,Trend_lag_12,Return,Year,Tikr_y,Nifty_Returns
0,20MICRONS,175.00,234.00,262.00,275.00,288.00,33.714286,11.965812,4.961832,4.727273,...,-8.900086,-2.150535,-0.125591,-3.175105,-0.689936,-0.809149,-17.771610,2015,NIFTY50,41.708545
1,21STCENMGM,1.18,23.45,-4.20,0.12,1.08,1887.288136,-117.910448,-102.857143,800.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2015,NIFTY50,41.708545
2,3IINFOTECH,692.00,963.00,1120.00,1198.00,1278.00,39.161850,16.303219,6.964286,6.677796,...,NaN,NaN,NaN,NaN,NaN,NaN,4.551384,2015,NIFTY50,41.708545
3,3MINDIA,1087.00,1191.00,1405.00,1574.00,1742.00,9.567617,17.968094,12.028470,10.673443,...,6.193921,17.388658,10.294305,-2.990968,5.465670,-0.208745,155.501282,2015,NIFTY50,41.708545
4,3PLAND,70.27,99.43,125.64,133.58,137.98,41.497083,26.360253,6.319643,3.293906,...,22.018740,-10.296682,-7.003894,-9.309623,-0.230679,-4.277458,NaN,2015,NIFTY50,41.708545

In [ ]:
df_final['Return_adj'] = df_final['Return'] - df_final['Nifty_Returns']
df_final.head(20)

,Tikr_x,Sales_yr_1,Sales_yr_2,Sales_yr_3,Sales_yr_4,Sales_yr_5,Sales_yr_2_YoY,Sales_yr_3_YoY,Sales_yr_4_YoY,Sales_yr_5_YoY,...,Trend_lag_08,Trend_lag_09,Trend_lag_10,Trend_lag_11,Trend_lag_12,Return,Year,Tikr_y,Nifty_Returns,Return_adj
0,20MICRONS,175.00,234.00,262.00,275.00,288.00,33.714286,11.965812,4.961832,4.727273,...,-2.150535,-0.125591,-3.175105,-0.689936,-0.809149,-17.771610,2015,NIFTY50,41.708545,-59.480156
1,21STCENMGM,1.18,23.45,-4.20,0.12,1.08,1887.288136,-117.910448,-102.857143,800.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,2015,NIFTY50,41.708545,NaN
2,3IINFOTECH,692.00,963.00,1120.00,1198.00,1278.00,39.161850,16.303219,6.964286,6.677796,...,NaN,NaN,NaN,NaN,NaN,4.551384,2015,NIFTY50,41.708545,-37.157161
3,3MINDIA,1087.00,1191.00,1405.00,1574.00,1742.00,9.567617,17.968094,12.028470,10.673443,...,17.388658,10.294305,-2.990968,5.465670,-0.208745,155.501282,2015,NIFTY50,41.708545,113.792736
4,3PLAND,70.27,99.43,125.64,133.58,137.98,41.497083,26.360253,6.319643,3.293906,...,-10.296682,-7.003894,-9.309623,-0.230679,-4.277458,NaN,2015,NIFTY50,41.708545,NaN
5,5PAISA,0.00,0.00,0.00,0.00,5.00,0.000000,0.000000,0.000000,inf,...,NaN,NaN,NaN,NaN,NaN,NaN,2015,NIFTY50,41.708545,NaN
6,63MOONS,307.00,358.00,426.00,451.00,335.00,16.612378,18.994413,5.868545,-25.720621,...,-5.729443,-11.402889,-14.184359,-8.162779,15.719535,NaN,2015,NIFTY50,41.708545,NaN
7,A2ZINFRA,1118.00,1107.00,968.00,555.00,336.00,-0.983900,-12.556459,-42.665289,-39.459459,...,-12.038913,-7.723503,-16.250501,5.664878,-18.284425,NaN,2015,NIFTY50,41.708545,NaN
8,AARTIDRUGS,460.00,496.00,659.00,826.00,972.00,7.826087,32.862903,25.341426,17.675545,...,22.534800,6.079971,-6.982465,13.319955,3.379235,405.441342,2015,NIFTY50,41.708545,363.732796
9,AARTIIND,1276.00,1427.00,1667.00,2086.00,2619.00,11.833856,16.818500,25.134973,25.551294,...,27.375668,8.879134,-2.519124,6.678936,-3.381639,354.813533,2015,NIFTY50,41.708545,313.104988
10,AARVEEDEN,375.00,495.00,661.00,723.00,685.00,32.000000,33.535354,9.379728,-5.255878,...,-3.540716,6.764551,-9.995088,4.365621,-3.518954,23.072107,2015,NIFTY50,41.708545,-18.636439
11,AAVAS,0.00,0.00,0.00,18.00,0.00,0.000000,0.000000,inf,-100.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,2015,NIFTY50,41.708545,NaN
12,ABAN,1182.00,1191.00,639.00,797.00,820.00,0.761421,-46.347607,24.726135,2.885822,...,-2.823351,-7.259103,-10.125874,-2.339082,-20.636441,21.660412,2015,NIFTY50,41.708545,-20.048133
13,ABB,6285.00,7447.00,7562.00,7719.00,7730.00,18.488465,1.544246,2.076170,0.142506,...,-5.205593,14.434131,-5.714255,2.579535,11.403424,119.078377,2015,NIFTY50,41.708545,77.369832
14,ABBOTINDIA,990.00,1490.00,1653.00,0.00,2276.00,50.505051,10.939597,-100.000000,inf,...,NaN,NaN,NaN,NaN,NaN,213.083505,2015,NIFTY50,41.708545,171.374960
15,ABCAPITAL,1.00,3.00,0.00,2.00,4.00,200.000000,-100.000000,inf,100.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,2015,NIFTY50,41.708545,NaN
16,ABFRL,14.00,13.00,17.00,1285.00,1661.00,-7.142857,30.769231,7458.823529,29.260700,...,-7.600288,10.053572,-1.671264,-0.990100,-3.375000,NaN,2015,NIFTY50,41.708545,NaN
17,ABMINTLTD,725.00,833.00,991.00,1052.00,1170.00,14.896552,18.967587,6.155399,11.216730,...,NaN,NaN,NaN,NaN,NaN,NaN,2015,NIFTY50,41.708545,NaN
18,ACC,7637.00,9576.00,11275.00,11061.00,11645.00,25.389551,17.742272,-1.898004,5.279812,...,5.164625,-0.390496,-2.146779,3.051833,-4.335300,21.800785,2015,NIFTY50,41.708545,-19.907760
19,ACCELYA,127.00,170.00,173.00,262.00,283.00,33.858268,1.764706,51.445087,8.015267,...,-8.505279,14.379825,8.540280,11.253243,15.551442,99.066763,2015,NIFTY50,41.708545,57.358218

In [59]:
df_final.to_csv('df_train_data_with_price.csv')

In [62]:
df_final[df_final['Tikr_x'] == '20MICRONS']

,Tikr_x,Sales_yr_1,Sales_yr_2,Sales_yr_3,Sales_yr_4,Sales_yr_5,Sales_yr_2_YoY,Sales_yr_3_YoY,Sales_yr_4_YoY,Sales_yr_5_YoY,...,Trend_lag_08,Trend_lag_09,Trend_lag_10,Trend_lag_11,Trend_lag_12,Return,Year,Tikr_y,Nifty_Returns,Return_adj
0,20MICRONS,175.0,234.0,262.0,275.0,288.0,33.714286,11.965812,4.961832,4.727273,...,-2.150535,-0.125591,-3.175105,-0.689936,-0.809149,-17.771610,2015,NIFTY50,41.708545,-59.480156
1619,20MICRONS,234.0,262.0,275.0,288.0,311.0,11.965812,4.961832,4.727273,7.986111,...,-7.913186,-8.584121,16.757560,-2.777069,6.787217,0.975626,2016,NIFTY50,10.551216,-9.575590
3238,20MICRONS,262.0,275.0,288.0,311.0,333.0,4.961832,4.727273,7.986111,7.073955,...,26.564098,1.127767,3.959936,-7.952210,-3.524077,31.130429,2017,NIFTY50,13.926248,17.204181
4857,20MICRONS,275.0,288.0,311.0,333.0,357.0,4.727273,7.986111,7.073955,7.207207,...,-9.003095,11.960376,13.957011,14.932327,10.910035,42.785607,2018,NIFTY50,32.721188,10.064419
6476,20MICRONS,288.0,311.0,333.0,357.0,385.0,7.986111,7.073955,7.207207,7.843137,...,24.504225,0.390236,-11.135808,5.560254,-2.728049,-9.439269,2019,NIFTY50,20.821578,-30.260847
8095,20MICRONS,311.0,333.0,357.0,385.0,436.0,7.073955,7.207207,7.843137,13.246753,...,-5.460416,11.269485,0.813986,-7.743218,-5.538020,-34.497100,2020,NIFTY50,0.752517,-35.249617
9714,20MICRONS,333.0,357.0,385.0,436.0,490.0,7.207207,7.843137,13.246753,12.385321,...,1.246966,-7.749522,-2.860858,15.484156,18.585783,35.556233,2021,NIFTY50,37.429123,-1.872890